services:
  reverseproxy: 
    image: reverseproxy
    ports:
      - 8080:8080
      - 8081:8081
    restart: always
  nginx: 
    image: nginx:alpine
    restart: always    
    depends_on:
      - reverseproxy
  apache: 
    image: httpd:alpine
    restart: always        
    depends_on:
      - reverseproxy
